// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TODO: Here and everywhere, s/Session/Actor to align with the glossary.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: ateapi.proto

package ateapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor_Status int32

const (
	Actor_STATUS_UNSPECIFIED Actor_Status = 0
	Actor_STATUS_RESUMING    Actor_Status = 1
	Actor_STATUS_RUNNING     Actor_Status = 2
	Actor_STATUS_SUSPENDING  Actor_Status = 3
	Actor_STATUS_SUSPENDED   Actor_Status = 4
	Actor_STATUS_PAUSING     Actor_Status = 5
	Actor_STATUS_PAUSED      Actor_Status = 6
	Actor_STATUS_CRASHED     Actor_Status = 7
)

// Enum value maps for Actor_Status.
var (
	Actor_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RESUMING",
		2: "STATUS_RUNNING",
		3: "STATUS_SUSPENDING",
		4: "STATUS_SUSPENDED",
		5: "STATUS_PAUSING",
		6: "STATUS_PAUSED",
		7: "STATUS_CRASHED",
	}
	Actor_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_RESUMING":    1,
		"STATUS_RUNNING":     2,
		"STATUS_SUSPENDING":  3,
		"STATUS_SUSPENDED":   4,
		"STATUS_PAUSING":     5,
		"STATUS_PAUSED":      6,
		"STATUS_CRASHED":     7,
	}
)

func (x Actor_Status) Enum() *Actor_Status {
	p := new(Actor_Status)
	*p = x
	return p
}

func (x Actor_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actor_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ateapi_proto_enumTypes[0].Descriptor()
}

func (Actor_Status) Type() protoreflect.EnumType {
	return &file_ateapi_proto_enumTypes[0]
}

func (x Actor_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actor_Status.Descriptor instead.
func (Actor_Status) EnumDescriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{5, 0}
}

type Worker_State int32

const (
	Worker_STATE_UNSPECIFIED Worker_State = 0
	Worker_STATE_ACTIVE      Worker_State = 1
	Worker_STATE_DRAINING    Worker_State = 2
)

// Enum value maps for Worker_State.
var (
	Worker_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_ACTIVE",
		2: "STATE_DRAINING",
	}
	Worker_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_ACTIVE":      1,
		"STATE_DRAINING":    2,
	}
)

func (x Worker_State) Enum() *Worker_State {
	p := new(Worker_State)
	*p = x
	return p
}

func (x Worker_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Worker_State) Descriptor() protoreflect.EnumDescriptor {
	return file_ateapi_proto_enumTypes[1].Descriptor()
}

func (Worker_State) Type() protoreflect.EnumType {
	return &file_ateapi_proto_enumTypes[1]
}

func (x Worker_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Worker_State.Descriptor instead.
func (Worker_State) EnumDescriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{28, 0}
}

type ExternalSnapshotInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotUriPrefix string                 `protobuf:"bytes,1,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalSnapshotInfo) Reset() {
	*x = ExternalSnapshotInfo{}
	mi := &file_ateapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalSnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalSnapshotInfo) ProtoMessage() {}

func (x *ExternalSnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalSnapshotInfo.ProtoReflect.Descriptor instead.
func (*ExternalSnapshotInfo) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalSnapshotInfo) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

type LocalSnapshotInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotPrefix string                 `protobuf:"bytes,1,opt,name=snapshot_prefix,json=snapshotPrefix,proto3" json:"snapshot_prefix,omitempty"`
	// Node VMs that have local snapshots for this actor, while it's PAUSED.
	NodeVmsWithLocalSnapshots []string `protobuf:"bytes,2,rep,name=node_vms_with_local_snapshots,json=nodeVmsWithLocalSnapshots,proto3" json:"node_vms_with_local_snapshots,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LocalSnapshotInfo) Reset() {
	*x = LocalSnapshotInfo{}
	mi := &file_ateapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSnapshotInfo) ProtoMessage() {}

func (x *LocalSnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSnapshotInfo.ProtoReflect.Descriptor instead.
func (*LocalSnapshotInfo) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{1}
}

func (x *LocalSnapshotInfo) GetSnapshotPrefix() string {
	if x != nil {
		return x.SnapshotPrefix
	}
	return ""
}

func (x *LocalSnapshotInfo) GetNodeVmsWithLocalSnapshots() []string {
	if x != nil {
		return x.NodeVmsWithLocalSnapshots
	}
	return nil
}

type SnapshotInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SnapshotInfo_External
	//	*SnapshotInfo_Local
	Data          isSnapshotInfo_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_ateapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotInfo) GetData() isSnapshotInfo_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotInfo) GetExternal() *ExternalSnapshotInfo {
	if x != nil {
		if x, ok := x.Data.(*SnapshotInfo_External); ok {
			return x.External
		}
	}
	return nil
}

func (x *SnapshotInfo) GetLocal() *LocalSnapshotInfo {
	if x != nil {
		if x, ok := x.Data.(*SnapshotInfo_Local); ok {
			return x.Local
		}
	}
	return nil
}

type isSnapshotInfo_Data interface {
	isSnapshotInfo_Data()
}

type SnapshotInfo_External struct {
	External *ExternalSnapshotInfo `protobuf:"bytes,2,opt,name=external,proto3,oneof"`
}

type SnapshotInfo_Local struct {
	Local *LocalSnapshotInfo `protobuf:"bytes,3,opt,name=local,proto3,oneof"`
}

func (*SnapshotInfo_External) isSnapshotInfo_Data() {}

func (*SnapshotInfo_Local) isSnapshotInfo_Data() {}

// Selector matches worker pools by label.
// Only equality-based matching is supported.
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchLabels   map[string]string      `protobuf:"bytes,1,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_ateapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{3}
}

func (x *Selector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

// ResourceMetadata holds the common fields carried by every Substrate resource.
type ResourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// atespace is the namespace the resource belongs to. Empty for global-scoped
	// resources. Caller-specified at creation and immutable thereafter.
	Atespace string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// name is the resource's name, unique within its atespace (or globally, for
	// global-scoped resources). Caller-specified at creation and immutable thereafter.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// uid is a server-assigned, globally unique identifier for this resource.
	// Immutable throughout the lifecycle of the resource.
	Uid string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// version is increased on every mutation.
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// create_time is the time the resource was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// update_time is the time the resource was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_ateapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceMetadata) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ResourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResourceMetadata) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ResourceMetadata) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common resource metadata: atespace, name, uid, version, timestamps.
	Metadata               *ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ActorTemplateNamespace string            `protobuf:"bytes,2,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string            `protobuf:"bytes,3,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	Status                 Actor_Status      `protobuf:"varint,4,opt,name=status,proto3,enum=ateapi.Actor_Status" json:"status,omitempty"`
	AteomPodNamespace      string            `protobuf:"bytes,5,opt,name=ateom_pod_namespace,json=ateomPodNamespace,proto3" json:"ateom_pod_namespace,omitempty"`
	AteomPodName           string            `protobuf:"bytes,6,opt,name=ateom_pod_name,json=ateomPodName,proto3" json:"ateom_pod_name,omitempty"`
	AteomPodIp             string            `protobuf:"bytes,7,opt,name=ateom_pod_ip,json=ateomPodIp,proto3" json:"ateom_pod_ip,omitempty"`
	InProgressSnapshot     string            `protobuf:"bytes,8,opt,name=in_progress_snapshot,json=inProgressSnapshot,proto3" json:"in_progress_snapshot,omitempty"`
	AteomPodUid            string            `protobuf:"bytes,9,opt,name=ateom_pod_uid,json=ateomPodUid,proto3" json:"ateom_pod_uid,omitempty"`
	LatestSnapshotInfo     *SnapshotInfo     `protobuf:"bytes,10,opt,name=latest_snapshot_info,json=latestSnapshotInfo,proto3" json:"latest_snapshot_info,omitempty"`
	// worker_selector is the per-actor placement constraint. The scheduler
	// evaluates the AND of this selector and the template's workerSelector to
	// find eligible pools. Set at CreateActor; may be updated at any time via
	// UpdateActor. Changes take effect on the next ResumeActor call.
	WorkerSelector *Selector `protobuf:"bytes,11,opt,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty"`
	// worker_pool_name is the name of the WorkerPool that owns the currently
	// assigned worker, in the same namespace as ateom_pod_namespace (pool and
	// pod namespaces always match). Set by the scheduler at assignment time
	// and cleared when the worker is freed. Needed to release the worker on
	// suspend/pause since eligibility is no longer a single fixed pool
	// reference on the ActorTemplate.
	WorkerPoolName string `protobuf:"bytes,12,opt,name=worker_pool_name,json=workerPoolName,proto3" json:"worker_pool_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_ateapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{5}
}

func (x *Actor) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Actor) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *Actor) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *Actor) GetStatus() Actor_Status {
	if x != nil {
		return x.Status
	}
	return Actor_STATUS_UNSPECIFIED
}

func (x *Actor) GetAteomPodNamespace() string {
	if x != nil {
		return x.AteomPodNamespace
	}
	return ""
}

func (x *Actor) GetAteomPodName() string {
	if x != nil {
		return x.AteomPodName
	}
	return ""
}

func (x *Actor) GetAteomPodIp() string {
	if x != nil {
		return x.AteomPodIp
	}
	return ""
}

func (x *Actor) GetInProgressSnapshot() string {
	if x != nil {
		return x.InProgressSnapshot
	}
	return ""
}

func (x *Actor) GetAteomPodUid() string {
	if x != nil {
		return x.AteomPodUid
	}
	return ""
}

func (x *Actor) GetLatestSnapshotInfo() *SnapshotInfo {
	if x != nil {
		return x.LatestSnapshotInfo
	}
	return nil
}

func (x *Actor) GetWorkerSelector() *Selector {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

func (x *Actor) GetWorkerPoolName() string {
	if x != nil {
		return x.WorkerPoolName
	}
	return ""
}

// Atespace is the isolation boundary an Actor is created into. Global-scoped:
// metadata.atespace is always empty; the atespace's identity is metadata.name.
type Atespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common resource metadata: name, uid, version, timestamps.
	Metadata      *ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Atespace) Reset() {
	*x = Atespace{}
	mi := &file_ateapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Atespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Atespace) ProtoMessage() {}

func (x *Atespace) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Atespace.ProtoReflect.Descriptor instead.
func (*Atespace) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{6}
}

func (x *Atespace) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ObjectRef references a Substrate resource by its (atespace, name) identity.
type ObjectRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The atespace where the resource lives. Empty if the resource is global-scoped.
	Atespace string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// The name of the resource. Required. Unique within an atespace, or globally
	// unique if the resource is global-scoped.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_ateapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectRef) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAtespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The atespace to create.
	Atespace      *Atespace `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAtespaceRequest) Reset() {
	*x = CreateAtespaceRequest{}
	mi := &file_ateapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAtespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAtespaceRequest) ProtoMessage() {}

func (x *CreateAtespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAtespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateAtespaceRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAtespaceRequest) GetAtespace() *Atespace {
	if x != nil {
		return x.Atespace
	}
	return nil
}

type GetAtespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      *ObjectRef             `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtespaceRequest) Reset() {
	*x = GetAtespaceRequest{}
	mi := &file_ateapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtespaceRequest) ProtoMessage() {}

func (x *GetAtespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtespaceRequest.ProtoReflect.Descriptor instead.
func (*GetAtespaceRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{9}
}

func (x *GetAtespaceRequest) GetAtespace() *ObjectRef {
	if x != nil {
		return x.Atespace
	}
	return nil
}

type ListAtespacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested page size; the server may return fewer, or occasionally
	// slightly more. If unspecified, defaults to a server-chosen value;
	// values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListAtespaces response.
	// Omit or leave empty for the first request.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAtespacesRequest) Reset() {
	*x = ListAtespacesRequest{}
	mi := &file_ateapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAtespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAtespacesRequest) ProtoMessage() {}

func (x *ListAtespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAtespacesRequest.ProtoReflect.Descriptor instead.
func (*ListAtespacesRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{10}
}

func (x *ListAtespacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAtespacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAtespacesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of atespaces. This list may be empty even if there are more results.
	Atespaces []*Atespace `protobuf:"bytes,1,rep,name=atespaces,proto3" json:"atespaces,omitempty"`
	// Pagination token for the next page. Empty if this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAtespacesResponse) Reset() {
	*x = ListAtespacesResponse{}
	mi := &file_ateapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAtespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAtespacesResponse) ProtoMessage() {}

func (x *ListAtespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAtespacesResponse.ProtoReflect.Descriptor instead.
func (*ListAtespacesResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{11}
}

func (x *ListAtespacesResponse) GetAtespaces() []*Atespace {
	if x != nil {
		return x.Atespaces
	}
	return nil
}

func (x *ListAtespacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteAtespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      *ObjectRef             `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAtespaceRequest) Reset() {
	*x = DeleteAtespaceRequest{}
	mi := &file_ateapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAtespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAtespaceRequest) ProtoMessage() {}

func (x *DeleteAtespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAtespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteAtespaceRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAtespaceRequest) GetAtespace() *ObjectRef {
	if x != nil {
		return x.Atespace
	}
	return nil
}

type GetActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	mi := &file_ateapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{13}
}

func (x *GetActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Request to create a new Actor.
type CreateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actor to create.
	Actor         *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorRequest) Reset() {
	*x = CreateActorRequest{}
	mi := &file_ateapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorRequest) ProtoMessage() {}

func (x *CreateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorRequest.ProtoReflect.Descriptor instead.
func (*CreateActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{14}
}

func (x *CreateActorRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Request to update mutable fields on an existing Actor.
// May be called regardless of the actor's current status.
// Changes take effect on the next ResumeActor call.
type UpdateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Actor *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	// worker_selector replaces the actor's current placement constraint.
	// Takes effect on the next ResumeActor call.
	WorkerSelector *Selector `protobuf:"bytes,2,opt,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateActorRequest) Reset() {
	*x = UpdateActorRequest{}
	mi := &file_ateapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActorRequest) ProtoMessage() {}

func (x *UpdateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActorRequest.ProtoReflect.Descriptor instead.
func (*UpdateActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *UpdateActorRequest) GetWorkerSelector() *Selector {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

type UpdateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActorResponse) Reset() {
	*x = UpdateActorResponse{}
	mi := &file_ateapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActorResponse) ProtoMessage() {}

func (x *UpdateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActorResponse.ProtoReflect.Descriptor instead.
func (*UpdateActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type SuspendActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorRequest) Reset() {
	*x = SuspendActorRequest{}
	mi := &file_ateapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorRequest) ProtoMessage() {}

func (x *SuspendActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorRequest.ProtoReflect.Descriptor instead.
func (*SuspendActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{17}
}

func (x *SuspendActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type SuspendActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorResponse) Reset() {
	*x = SuspendActorResponse{}
	mi := &file_ateapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorResponse) ProtoMessage() {}

func (x *SuspendActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorResponse.ProtoReflect.Descriptor instead.
func (*SuspendActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{18}
}

func (x *SuspendActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type PauseActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseActorRequest) Reset() {
	*x = PauseActorRequest{}
	mi := &file_ateapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseActorRequest) ProtoMessage() {}

func (x *PauseActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseActorRequest.ProtoReflect.Descriptor instead.
func (*PauseActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{19}
}

func (x *PauseActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type PauseActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseActorResponse) Reset() {
	*x = PauseActorResponse{}
	mi := &file_ateapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseActorResponse) ProtoMessage() {}

func (x *PauseActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseActorResponse.ProtoReflect.Descriptor instead.
func (*PauseActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{20}
}

func (x *PauseActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ResumeActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Actor *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	// If true, skip golden snapshot and boot the workload from scratch.
	Boot          bool `protobuf:"varint,2,opt,name=boot,proto3" json:"boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorRequest) Reset() {
	*x = ResumeActorRequest{}
	mi := &file_ateapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorRequest) ProtoMessage() {}

func (x *ResumeActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorRequest.ProtoReflect.Descriptor instead.
func (*ResumeActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{21}
}

func (x *ResumeActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ResumeActorRequest) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type ResumeActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorResponse) Reset() {
	*x = ResumeActorResponse{}
	mi := &file_ateapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorResponse) ProtoMessage() {}

func (x *ResumeActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorResponse.ProtoReflect.Descriptor instead.
func (*ResumeActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{22}
}

func (x *ResumeActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type DeleteActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ObjectRef             `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActorRequest) Reset() {
	*x = DeleteActorRequest{}
	mi := &file_ateapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActorRequest) ProtoMessage() {}

func (x *DeleteActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActorRequest.ProtoReflect.Descriptor instead.
func (*DeleteActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListWorkersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested page size; the server may return fewer, or occasionally
	// slightly more. If unspecified, defaults to a server-chosen value;
	// values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListWorkers response.
	// Omit or leave empty for the first request.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_ateapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{24}
}

func (x *ListWorkersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of workers. This list may be empty even if there are more results.
	Workers []*Worker `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	// Pagination token for the next page. Empty if this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_ateapi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{25}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ListWorkersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// List actors with pagination. Provides "soft" guarantees: actors may be
// missed or duplicated if the system state changes during pagination.
type ListActorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The atespace to list actors from. Empty lists across all atespaces.
	Atespace string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// Requested page size; the server may return fewer, or occasionally
	// slightly more. If unspecified, defaults to a server-chosen value;
	// values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListActors response.
	// Omit or leave empty for the first request.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	mi := &file_ateapi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{26}
}

func (x *ListActorsRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ListActorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActorsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListActorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of actors. This list may be empty even if there are more results.
	Actors []*Actor `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	// Pagination token for the next page. Empty if this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	mi := &file_ateapi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{27}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *ListActorsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Worker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerNamespace string                 `protobuf:"bytes,1,opt,name=worker_namespace,json=workerNamespace,proto3" json:"worker_namespace,omitempty"`
	WorkerPool      string                 `protobuf:"bytes,2,opt,name=worker_pool,json=workerPool,proto3" json:"worker_pool,omitempty"`
	WorkerPod       string                 `protobuf:"bytes,3,opt,name=worker_pod,json=workerPod,proto3" json:"worker_pod,omitempty"`
	Assignment      *Assignment            `protobuf:"bytes,4,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Ip              string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Version         int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	WorkerPodUid    string                 `protobuf:"bytes,7,opt,name=worker_pod_uid,json=workerPodUid,proto3" json:"worker_pod_uid,omitempty"`
	NodeName        string                 `protobuf:"bytes,8,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	SandboxClass    string                 `protobuf:"bytes,9,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State           Worker_State           `protobuf:"varint,11,opt,name=state,proto3,enum=ateapi.Worker_State" json:"state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_ateapi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{28}
}

func (x *Worker) GetWorkerNamespace() string {
	if x != nil {
		return x.WorkerNamespace
	}
	return ""
}

func (x *Worker) GetWorkerPool() string {
	if x != nil {
		return x.WorkerPool
	}
	return ""
}

func (x *Worker) GetWorkerPod() string {
	if x != nil {
		return x.WorkerPod
	}
	return ""
}

func (x *Worker) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *Worker) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Worker) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Worker) GetWorkerPodUid() string {
	if x != nil {
		return x.WorkerPodUid
	}
	return ""
}

func (x *Worker) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Worker) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *Worker) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Worker) GetState() Worker_State {
	if x != nil {
		return x.State
	}
	return Worker_STATE_UNSPECIFIED
}

type Assignment struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ActorTemplate *KubeNamespacedObjectRef `protobuf:"bytes,1,opt,name=actor_template,json=actorTemplate,proto3" json:"actor_template,omitempty"`
	Actor         *ObjectRef               `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_ateapi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{29}
}

func (x *Assignment) GetActorTemplate() *KubeNamespacedObjectRef {
	if x != nil {
		return x.ActorTemplate
	}
	return nil
}

func (x *Assignment) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type KubeNamespacedObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeNamespacedObjectRef) Reset() {
	*x = KubeNamespacedObjectRef{}
	mi := &file_ateapi_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeNamespacedObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeNamespacedObjectRef) ProtoMessage() {}

func (x *KubeNamespacedObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeNamespacedObjectRef.ProtoReflect.Descriptor instead.
func (*KubeNamespacedObjectRef) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{30}
}

func (x *KubeNamespacedObjectRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeNamespacedObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DebugClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearRequest) Reset() {
	*x = DebugClearRequest{}
	mi := &file_ateapi_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearRequest) ProtoMessage() {}

func (x *DebugClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearRequest.ProtoReflect.Descriptor instead.
func (*DebugClearRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{31}
}

type DebugClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearResponse) Reset() {
	*x = DebugClearResponse{}
	mi := &file_ateapi_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearResponse) ProtoMessage() {}

func (x *DebugClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearResponse.ProtoReflect.Descriptor instead.
func (*DebugClearResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{32}
}

type MintJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      []string               `protobuf:"bytes,1,rep,name=audience,proto3" json:"audience,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTRequest) Reset() {
	*x = MintJWTRequest{}
	mi := &file_ateapi_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTRequest) ProtoMessage() {}

func (x *MintJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTRequest.ProtoReflect.Descriptor instead.
func (*MintJWTRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{33}
}

func (x *MintJWTRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *MintJWTRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintJWTRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintJWTRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MintJWTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session JWT.  An OIDC Discovery-compatible JWT
	//
	// Claims:
	//
	//   - iss: Issuer - a valid URL where a relying party can fetch the OIDC
	//     discovery documents.
	//   - sub: Subject - a string expressing the identity carried in the
	//
	// credential. Format
	//
	//	`app/${appid}/user/${userid}/session/${sessionid}`.
	//   - aud: Audience - a string identifying the service this token will be used
	//     to authenticate to.
	//   - nbf: Not Before - a numeric unix timestamp
	//   - exp: Expiration - a numeric unix timestamp
	//   - iat: Issued At - a numeric unix timestamp
	//   - `ate.dev`: Ate/Substrate Extension - JSON object
	//   - appID: (string) The Substrate App ID
	//   - userID: (string) The Substrate User ID
	//   - sessionID: (string) The Substrate Session ID
	SessionJwt    string `protobuf:"bytes,1,opt,name=session_jwt,json=sessionJwt,proto3" json:"session_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTResponse) Reset() {
	*x = MintJWTResponse{}
	mi := &file_ateapi_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTResponse) ProtoMessage() {}

func (x *MintJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTResponse.ProtoReflect.Descriptor instead.
func (*MintJWTResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{34}
}

func (x *MintJWTResponse) GetSessionJwt() string {
	if x != nil {
		return x.SessionJwt
	}
	return ""
}

type MintCertRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Request contains DER encoded bytes of a x509 certificate signing request.
	// The signer will ignore the contents of the CSR except to extract the
	// subject public key.
	CertificateSigningRequest []byte `protobuf:"bytes,4,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MintCertRequest) Reset() {
	*x = MintCertRequest{}
	mi := &file_ateapi_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertRequest) ProtoMessage() {}

func (x *MintCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertRequest.ProtoReflect.Descriptor instead.
func (*MintCertRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{35}
}

func (x *MintCertRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintCertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintCertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MintCertRequest) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.CertificateSigningRequest
	}
	return nil
}

type MintCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response contains a list of DER encoded certificates. The first entry is the
	// leaf certificate, and any remaining entries are intermediates in
	// leaf-to-root order.
	SessionCertificates [][]byte `protobuf:"bytes,1,rep,name=session_certificates,json=sessionCertificates,proto3" json:"session_certificates,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MintCertResponse) Reset() {
	*x = MintCertResponse{}
	mi := &file_ateapi_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertResponse) ProtoMessage() {}

func (x *MintCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertResponse.ProtoReflect.Descriptor instead.
func (*MintCertResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{36}
}

func (x *MintCertResponse) GetSessionCertificates() [][]byte {
	if x != nil {
		return x.SessionCertificates
	}
	return nil
}

var File_ateapi_proto protoreflect.FileDescriptor

const file_ateapi_proto_rawDesc = "" +
	"\n" +
	"\fateapi.proto\x12\x06ateapi\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x14ExternalSnapshotInfo\x12.\n" +
	"\x13snapshot_uri_prefix\x18\x01 \x01(\tR\x11snapshotUriPrefix\"~\n" +
	"\x11LocalSnapshotInfo\x12'\n" +
	"\x0fsnapshot_prefix\x18\x01 \x01(\tR\x0esnapshotPrefix\x12@\n" +
	"\x1dnode_vms_with_local_snapshots\x18\x02 \x03(\tR\x19nodeVmsWithLocalSnapshots\"\x91\x01\n" +
	"\fSnapshotInfo\x12:\n" +
	"\bexternal\x18\x02 \x01(\v2\x1c.ateapi.ExternalSnapshotInfoH\x00R\bexternal\x121\n" +
	"\x05local\x18\x03 \x01(\v2\x19.ateapi.LocalSnapshotInfoH\x00R\x05localB\x06\n" +
	"\x04dataJ\x04\b\x01\x10\x02R\x04type\"\x90\x01\n" +
	"\bSelector\x12D\n" +
	"\fmatch_labels\x18\x01 \x03(\v2!.ateapi.Selector.MatchLabelsEntryR\vmatchLabels\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x10ResourceMetadata\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x84\x06\n" +
	"\x05Actor\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.ateapi.ResourceMetadataR\bmetadata\x128\n" +
	"\x18actor_template_namespace\x18\x02 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x03 \x01(\tR\x11actorTemplateName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.ateapi.Actor.StatusR\x06status\x12.\n" +
	"\x13ateom_pod_namespace\x18\x05 \x01(\tR\x11ateomPodNamespace\x12$\n" +
	"\x0eateom_pod_name\x18\x06 \x01(\tR\fateomPodName\x12 \n" +
	"\fateom_pod_ip\x18\a \x01(\tR\n" +
	"ateomPodIp\x120\n" +
	"\x14in_progress_snapshot\x18\b \x01(\tR\x12inProgressSnapshot\x12\"\n" +
	"\rateom_pod_uid\x18\t \x01(\tR\vateomPodUid\x12F\n" +
	"\x14latest_snapshot_info\x18\n" +
	" \x01(\v2\x14.ateapi.SnapshotInfoR\x12latestSnapshotInfo\x129\n" +
	"\x0fworker_selector\x18\v \x01(\v2\x10.ateapi.SelectorR\x0eworkerSelector\x12(\n" +
	"\x10worker_pool_name\x18\f \x01(\tR\x0eworkerPoolName\"\xb1\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_RESUMING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x15\n" +
	"\x11STATUS_SUSPENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_PAUSING\x10\x05\x12\x11\n" +
	"\rSTATUS_PAUSED\x10\x06\x12\x12\n" +
	"\x0eSTATUS_CRASHED\x10\a\"@\n" +
	"\bAtespace\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.ateapi.ResourceMetadataR\bmetadata\";\n" +
	"\tObjectRef\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"E\n" +
	"\x15CreateAtespaceRequest\x12,\n" +
	"\batespace\x18\x01 \x01(\v2\x10.ateapi.AtespaceR\batespace\"C\n" +
	"\x12GetAtespaceRequest\x12-\n" +
	"\batespace\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\batespace\"R\n" +
	"\x14ListAtespacesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\x15ListAtespacesResponse\x12.\n" +
	"\tatespaces\x18\x01 \x03(\v2\x10.ateapi.AtespaceR\tatespaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"F\n" +
	"\x15DeleteAtespaceRequest\x12-\n" +
	"\batespace\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\batespace\":\n" +
	"\x0fGetActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\"9\n" +
	"\x12CreateActorRequest\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"x\n" +
	"\x12UpdateActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\x129\n" +
	"\x0fworker_selector\x18\x02 \x01(\v2\x10.ateapi.SelectorR\x0eworkerSelector\":\n" +
	"\x13UpdateActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\">\n" +
	"\x13SuspendActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\";\n" +
	"\x14SuspendActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"<\n" +
	"\x11PauseActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\"9\n" +
	"\x12PauseActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"Q\n" +
	"\x12ResumeActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\x12\x12\n" +
	"\x04boot\x18\x02 \x01(\bR\x04boot\":\n" +
	"\x13ResumeActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"=\n" +
	"\x12DeleteActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\"P\n" +
	"\x12ListWorkersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"g\n" +
	"\x13ListWorkersResponse\x12(\n" +
	"\aworkers\x18\x01 \x03(\v2\x0e.ateapi.WorkerR\aworkers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"k\n" +
	"\x11ListActorsRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"c\n" +
	"\x12ListActorsResponse\x12%\n" +
	"\x06actors\x18\x01 \x03(\v2\r.ateapi.ActorR\x06actors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9a\x04\n" +
	"\x06Worker\x12)\n" +
	"\x10worker_namespace\x18\x01 \x01(\tR\x0fworkerNamespace\x12\x1f\n" +
	"\vworker_pool\x18\x02 \x01(\tR\n" +
	"workerPool\x12\x1d\n" +
	"\n" +
	"worker_pod\x18\x03 \x01(\tR\tworkerPod\x122\n" +
	"\n" +
	"assignment\x18\x04 \x01(\v2\x12.ateapi.AssignmentR\n" +
	"assignment\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12$\n" +
	"\x0eworker_pod_uid\x18\a \x01(\tR\fworkerPodUid\x12\x1b\n" +
	"\tnode_name\x18\b \x01(\tR\bnodeName\x12#\n" +
	"\rsandbox_class\x18\t \x01(\tR\fsandboxClass\x122\n" +
	"\x06labels\x18\n" +
	" \x03(\v2\x1a.ateapi.Worker.LabelsEntryR\x06labels\x12*\n" +
	"\x05state\x18\v \x01(\x0e2\x14.ateapi.Worker.StateR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eSTATE_DRAINING\x10\x02\"}\n" +
	"\n" +
	"Assignment\x12F\n" +
	"\x0eactor_template\x18\x01 \x01(\v2\x1f.ateapi.KubeNamespacedObjectRefR\ractorTemplate\x12'\n" +
	"\x05actor\x18\x02 \x01(\v2\x11.ateapi.ObjectRefR\x05actor\"K\n" +
	"\x17KubeNamespacedObjectRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x13\n" +
	"\x11DebugClearRequest\"\x14\n" +
	"\x12DebugClearResponse\"{\n" +
	"\x0eMintJWTRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x03(\tR\baudience\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"2\n" +
	"\x0fMintJWTResponse\x12\x1f\n" +
	"\vsession_jwt\x18\x01 \x01(\tR\n" +
	"sessionJwt\"\xa0\x01\n" +
	"\x0fMintCertRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12>\n" +
	"\x1bcertificate_signing_request\x18\x04 \x01(\fR\x19certificateSigningRequest\"E\n" +
	"\x10MintCertResponse\x121\n" +
	"\x14session_certificates\x18\x01 \x03(\fR\x13sessionCertificates2\x89\a\n" +
	"\aControl\x124\n" +
	"\bGetActor\x12\x17.ateapi.GetActorRequest\x1a\r.ateapi.Actor\"\x00\x12:\n" +
	"\vCreateActor\x12\x1a.ateapi.CreateActorRequest\x1a\r.ateapi.Actor\"\x00\x12H\n" +
	"\vUpdateActor\x12\x1a.ateapi.UpdateActorRequest\x1a\x1b.ateapi.UpdateActorResponse\"\x00\x12K\n" +
	"\fSuspendActor\x12\x1b.ateapi.SuspendActorRequest\x1a\x1c.ateapi.SuspendActorResponse\"\x00\x12E\n" +
	"\n" +
	"PauseActor\x12\x19.ateapi.PauseActorRequest\x1a\x1a.ateapi.PauseActorResponse\"\x00\x12H\n" +
	"\vResumeActor\x12\x1a.ateapi.ResumeActorRequest\x1a\x1b.ateapi.ResumeActorResponse\"\x00\x12:\n" +
	"\vDeleteActor\x12\x1a.ateapi.DeleteActorRequest\x1a\r.ateapi.Actor\"\x00\x12H\n" +
	"\vListWorkers\x12\x1a.ateapi.ListWorkersRequest\x1a\x1b.ateapi.ListWorkersResponse\"\x00\x12E\n" +
	"\n" +
	"ListActors\x12\x19.ateapi.ListActorsRequest\x1a\x1a.ateapi.ListActorsResponse\"\x00\x12C\n" +
	"\x0eCreateAtespace\x12\x1d.ateapi.CreateAtespaceRequest\x1a\x10.ateapi.Atespace\"\x00\x12=\n" +
	"\vGetAtespace\x12\x1a.ateapi.GetAtespaceRequest\x1a\x10.ateapi.Atespace\"\x00\x12N\n" +
	"\rListAtespaces\x12\x1c.ateapi.ListAtespacesRequest\x1a\x1d.ateapi.ListAtespacesResponse\"\x00\x12C\n" +
	"\x0eDeleteAtespace\x12\x1d.ateapi.DeleteAtespaceRequest\x1a\x10.ateapi.Atespace\"\x002N\n" +
	"\x05Debug\x12E\n" +
	"\n" +
	"DebugClear\x12\x19.ateapi.DebugClearRequest\x1a\x1a.ateapi.DebugClearResponse\"\x002\x8c\x01\n" +
	"\x0fSessionIdentity\x12:\n" +
	"\aMintJWT\x12\x16.ateapi.MintJWTRequest\x1a\x17.ateapi.MintJWTResponse\x12=\n" +
	"\bMintCert\x12\x17.ateapi.MintCertRequest\x1a\x18.ateapi.MintCertResponseB9Z7github.com/agent-substrate/substrate/pkg/proto/ateapipbb\x06proto3"

var (
	file_ateapi_proto_rawDescOnce sync.Once
	file_ateapi_proto_rawDescData []byte
)

func file_ateapi_proto_rawDescGZIP() []byte {
	file_ateapi_proto_rawDescOnce.Do(func() {
		file_ateapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateapi_proto_rawDesc), len(file_ateapi_proto_rawDesc)))
	})
	return file_ateapi_proto_rawDescData
}

var file_ateapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ateapi_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_ateapi_proto_goTypes = []any{
	(Actor_Status)(0),               // 0: ateapi.Actor.Status
	(Worker_State)(0),               // 1: ateapi.Worker.State
	(*ExternalSnapshotInfo)(nil),    // 2: ateapi.ExternalSnapshotInfo
	(*LocalSnapshotInfo)(nil),       // 3: ateapi.LocalSnapshotInfo
	(*SnapshotInfo)(nil),            // 4: ateapi.SnapshotInfo
	(*Selector)(nil),                // 5: ateapi.Selector
	(*ResourceMetadata)(nil),        // 6: ateapi.ResourceMetadata
	(*Actor)(nil),                   // 7: ateapi.Actor
	(*Atespace)(nil),                // 8: ateapi.Atespace
	(*ObjectRef)(nil),               // 9: ateapi.ObjectRef
	(*CreateAtespaceRequest)(nil),   // 10: ateapi.CreateAtespaceRequest
	(*GetAtespaceRequest)(nil),      // 11: ateapi.GetAtespaceRequest
	(*ListAtespacesRequest)(nil),    // 12: ateapi.ListAtespacesRequest
	(*ListAtespacesResponse)(nil),   // 13: ateapi.ListAtespacesResponse
	(*DeleteAtespaceRequest)(nil),   // 14: ateapi.DeleteAtespaceRequest
	(*GetActorRequest)(nil),         // 15: ateapi.GetActorRequest
	(*CreateActorRequest)(nil),      // 16: ateapi.CreateActorRequest
	(*UpdateActorRequest)(nil),      // 17: ateapi.UpdateActorRequest
	(*UpdateActorResponse)(nil),     // 18: ateapi.UpdateActorResponse
	(*SuspendActorRequest)(nil),     // 19: ateapi.SuspendActorRequest
	(*SuspendActorResponse)(nil),    // 20: ateapi.SuspendActorResponse
	(*PauseActorRequest)(nil),       // 21: ateapi.PauseActorRequest
	(*PauseActorResponse)(nil),      // 22: ateapi.PauseActorResponse
	(*ResumeActorRequest)(nil),      // 23: ateapi.ResumeActorRequest
	(*ResumeActorResponse)(nil),     // 24: ateapi.ResumeActorResponse
	(*DeleteActorRequest)(nil),      // 25: ateapi.DeleteActorRequest
	(*ListWorkersRequest)(nil),      // 26: ateapi.ListWorkersRequest
	(*ListWorkersResponse)(nil),     // 27: ateapi.ListWorkersResponse
	(*ListActorsRequest)(nil),       // 28: ateapi.ListActorsRequest
	(*ListActorsResponse)(nil),      // 29: ateapi.ListActorsResponse
	(*Worker)(nil),                  // 30: ateapi.Worker
	(*Assignment)(nil),              // 31: ateapi.Assignment
	(*KubeNamespacedObjectRef)(nil), // 32: ateapi.KubeNamespacedObjectRef
	(*DebugClearRequest)(nil),       // 33: ateapi.DebugClearRequest
	(*DebugClearResponse)(nil),      // 34: ateapi.DebugClearResponse
	(*MintJWTRequest)(nil),          // 35: ateapi.MintJWTRequest
	(*MintJWTResponse)(nil),         // 36: ateapi.MintJWTResponse
	(*MintCertRequest)(nil),         // 37: ateapi.MintCertRequest
	(*MintCertResponse)(nil),        // 38: ateapi.MintCertResponse
	nil,                             // 39: ateapi.Selector.MatchLabelsEntry
	nil,                             // 40: ateapi.Worker.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 41: google.protobuf.Timestamp
}
var file_ateapi_proto_depIdxs = []int32{
	2,  // 0: ateapi.SnapshotInfo.external:type_name -> ateapi.ExternalSnapshotInfo
	3,  // 1: ateapi.SnapshotInfo.local:type_name -> ateapi.LocalSnapshotInfo
	39, // 2: ateapi.Selector.match_labels:type_name -> ateapi.Selector.MatchLabelsEntry
	41, // 3: ateapi.ResourceMetadata.create_time:type_name -> google.protobuf.Timestamp
	41, // 4: ateapi.ResourceMetadata.update_time:type_name -> google.protobuf.Timestamp
	6,  // 5: ateapi.Actor.metadata:type_name -> ateapi.ResourceMetadata
	0,  // 6: ateapi.Actor.status:type_name -> ateapi.Actor.Status
	4,  // 7: ateapi.Actor.latest_snapshot_info:type_name -> ateapi.SnapshotInfo
	5,  // 8: ateapi.Actor.worker_selector:type_name -> ateapi.Selector
	6,  // 9: ateapi.Atespace.metadata:type_name -> ateapi.ResourceMetadata
	8,  // 10: ateapi.CreateAtespaceRequest.atespace:type_name -> ateapi.Atespace
	9,  // 11: ateapi.GetAtespaceRequest.atespace:type_name -> ateapi.ObjectRef
	8,  // 12: ateapi.ListAtespacesResponse.atespaces:type_name -> ateapi.Atespace
	9,  // 13: ateapi.DeleteAtespaceRequest.atespace:type_name -> ateapi.ObjectRef
	9,  // 14: ateapi.GetActorRequest.actor:type_name -> ateapi.ObjectRef
	7,  // 15: ateapi.CreateActorRequest.actor:type_name -> ateapi.Actor
	9,  // 16: ateapi.UpdateActorRequest.actor:type_name -> ateapi.ObjectRef
	5,  // 17: ateapi.UpdateActorRequest.worker_selector:type_name -> ateapi.Selector
	7,  // 18: ateapi.UpdateActorResponse.actor:type_name -> ateapi.Actor
	9,  // 19: ateapi.SuspendActorRequest.actor:type_name -> ateapi.ObjectRef
	7,  // 20: ateapi.SuspendActorResponse.actor:type_name -> ateapi.Actor
	9,  // 21: ateapi.PauseActorRequest.actor:type_name -> ateapi.ObjectRef
	7,  // 22: ateapi.PauseActorResponse.actor:type_name -> ateapi.Actor
	9,  // 23: ateapi.ResumeActorRequest.actor:type_name -> ateapi.ObjectRef
	7,  // 24: ateapi.ResumeActorResponse.actor:type_name -> ateapi.Actor
	9,  // 25: ateapi.DeleteActorRequest.actor:type_name -> ateapi.ObjectRef
	30, // 26: ateapi.ListWorkersResponse.workers:type_name -> ateapi.Worker
	7,  // 27: ateapi.ListActorsResponse.actors:type_name -> ateapi.Actor
	31, // 28: ateapi.Worker.assignment:type_name -> ateapi.Assignment
	40, // 29: ateapi.Worker.labels:type_name -> ateapi.Worker.LabelsEntry
	1,  // 30: ateapi.Worker.state:type_name -> ateapi.Worker.State
	32, // 31: ateapi.Assignment.actor_template:type_name -> ateapi.KubeNamespacedObjectRef
	9,  // 32: ateapi.Assignment.actor:type_name -> ateapi.ObjectRef
	15, // 33: ateapi.Control.GetActor:input_type -> ateapi.GetActorRequest
	16, // 34: ateapi.Control.CreateActor:input_type -> ateapi.CreateActorRequest
	17, // 35: ateapi.Control.UpdateActor:input_type -> ateapi.UpdateActorRequest
	19, // 36: ateapi.Control.SuspendActor:input_type -> ateapi.SuspendActorRequest
	21, // 37: ateapi.Control.PauseActor:input_type -> ateapi.PauseActorRequest
	23, // 38: ateapi.Control.ResumeActor:input_type -> ateapi.ResumeActorRequest
	25, // 39: ateapi.Control.DeleteActor:input_type -> ateapi.DeleteActorRequest
	26, // 40: ateapi.Control.ListWorkers:input_type -> ateapi.ListWorkersRequest
	28, // 41: ateapi.Control.ListActors:input_type -> ateapi.ListActorsRequest
	10, // 42: ateapi.Control.CreateAtespace:input_type -> ateapi.CreateAtespaceRequest
	11, // 43: ateapi.Control.GetAtespace:input_type -> ateapi.GetAtespaceRequest
	12, // 44: ateapi.Control.ListAtespaces:input_type -> ateapi.ListAtespacesRequest
	14, // 45: ateapi.Control.DeleteAtespace:input_type -> ateapi.DeleteAtespaceRequest
	33, // 46: ateapi.Debug.DebugClear:input_type -> ateapi.DebugClearRequest
	35, // 47: ateapi.SessionIdentity.MintJWT:input_type -> ateapi.MintJWTRequest
	37, // 48: ateapi.SessionIdentity.MintCert:input_type -> ateapi.MintCertRequest
	7,  // 49: ateapi.Control.GetActor:output_type -> ateapi.Actor
	7,  // 50: ateapi.Control.CreateActor:output_type -> ateapi.Actor
	18, // 51: ateapi.Control.UpdateActor:output_type -> ateapi.UpdateActorResponse
	20, // 52: ateapi.Control.SuspendActor:output_type -> ateapi.SuspendActorResponse
	22, // 53: ateapi.Control.PauseActor:output_type -> ateapi.PauseActorResponse
	24, // 54: ateapi.Control.ResumeActor:output_type -> ateapi.ResumeActorResponse
	7,  // 55: ateapi.Control.DeleteActor:output_type -> ateapi.Actor
	27, // 56: ateapi.Control.ListWorkers:output_type -> ateapi.ListWorkersResponse
	29, // 57: ateapi.Control.ListActors:output_type -> ateapi.ListActorsResponse
	8,  // 58: ateapi.Control.CreateAtespace:output_type -> ateapi.Atespace
	8,  // 59: ateapi.Control.GetAtespace:output_type -> ateapi.Atespace
	13, // 60: ateapi.Control.ListAtespaces:output_type -> ateapi.ListAtespacesResponse
	8,  // 61: ateapi.Control.DeleteAtespace:output_type -> ateapi.Atespace
	34, // 62: ateapi.Debug.DebugClear:output_type -> ateapi.DebugClearResponse
	36, // 63: ateapi.SessionIdentity.MintJWT:output_type -> ateapi.MintJWTResponse
	38, // 64: ateapi.SessionIdentity.MintCert:output_type -> ateapi.MintCertResponse
	49, // [49:65] is the sub-list for method output_type
	33, // [33:49] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_ateapi_proto_init() }
func file_ateapi_proto_init() {
	if File_ateapi_proto != nil {
		return
	}
	file_ateapi_proto_msgTypes[2].OneofWrappers = []any{
		(*SnapshotInfo_External)(nil),
		(*SnapshotInfo_Local)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateapi_proto_rawDesc), len(file_ateapi_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ateapi_proto_goTypes,
		DependencyIndexes: file_ateapi_proto_depIdxs,
		EnumInfos:         file_ateapi_proto_enumTypes,
		MessageInfos:      file_ateapi_proto_msgTypes,
	}.Build()
	File_ateapi_proto = out.File
	file_ateapi_proto_goTypes = nil
	file_ateapi_proto_depIdxs = nil
}
